source 'http://rubygems.org'

gem 'rails', '3.0.6'
gem 'mysql2', '0.2.7'
gem 'devise'
gem 'annotate'
gem 'formtastic'
gem 'oa-oauth', :require => 'omniauth/oauth'
gem 'paperclip', :git => 'https://github.com/thoughtbot/paperclip.git'
gem 'haml'
gem 'inherited_resources'
gem 'meta_search'
gem 'rmagick', '2.12.2'
gem 'state_machine'
gem 'will_paginate', '~> 3.0'
gem 'activemerchant'
gem 'sqlite3'
gem 'activeadmin'
gem 'rails3-jquery-autocomplete'
gem 'ruby-debug19', :require => 'ruby-debug'
gem 'airbrake', '~> 3.0.9'

group :development, :test do
  gem 'cucumber-rails'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'pickle'
  gem 'launchy'
  gem 'capistrano'
  gem 'engineyard'
end
